/* Generated by prototype/runs/site_dataset.py — do not hand-edit.
   Every number here is real output against a live site: stage-1 crawl
   for SURFACES, stage-2a autocomplete mining for EXPANSION.
   20 surfaces; 2 dropped for returning no pages. */
export const SURFACES = [
 {
  "domain": "graphonomous.com",
  "entity": "Agent memory that improves itself",
  "pages": 30,
  "words": 45939,
  "claims": 2826,
  "types": {
   "entity": 0,
   "quantity": 171,
   "quote": 137,
   "definition": 153,
   "comparison": 64,
   "question": 1,
   "credential": 146,
   "process": 0,
   "attribute": 2154
  },
  "blocked": [],
  "forms": [
   {
    "name": "Statistics / data page",
    "type": "quantity",
    "need": 5,
    "have": 171,
    "ok": true
   },
   {
    "name": "Glossary / definitions",
    "type": "definition",
    "need": 3,
    "have": 153,
    "ok": true
   },
   {
    "name": "FAQ page",
    "type": "question",
    "need": 5,
    "have": 1,
    "ok": false
   },
   {
    "name": "Comparison page",
    "type": "comparison",
    "need": 6,
    "have": 64,
    "ok": true
   },
   {
    "name": "How-it-works explainer",
    "type": "process",
    "need": 1,
    "have": 0,
    "ok": false
   },
   {
    "name": "Entity / about page",
    "type": "credential",
    "need": 3,
    "have": 146,
    "ok": true
   }
  ],
  "findings": {
   "contradictions": 0,
   "duplicate_urls": 1,
   "orphans": 15,
   "unsourced": 0,
   "spa": 7,
   "no_schema": 30
  },
  "material": [
   {
    "type": "quantity",
    "text": "But 95% score positively \u2014 the remaining 15.5pp come from cross-conversation entity bridging, where the answer content is surfaced through graph edges even when the top ANN hits are from different conversations.",
    "url": "https://graphonomous.com/benchmarks/beam.html"
   },
   {
    "type": "quantity",
    "text": "Evidence: rubric_score and nugget_proxy are identical across all tiers (95.0%, 97.5%, 96.9%), confirming that rubric matching is the primary scoring path and that it correlates perfectly with retrieval quality.",
    "url": "https://graphonomous.com/benchmarks/beam.html"
   }
  ]
 },
 {
  "domain": "opensentience.org",
  "entity": "OpenSentience",
  "pages": 16,
  "words": 12322,
  "claims": 539,
  "types": {
   "entity": 0,
   "quantity": 32,
   "quote": 25,
   "definition": 71,
   "comparison": 18,
   "question": 0,
   "credential": 0,
   "process": 0,
   "attribute": 393
  },
  "blocked": [],
  "forms": [
   {
    "name": "Statistics / data page",
    "type": "quantity",
    "need": 5,
    "have": 32,
    "ok": true
   },
   {
    "name": "Glossary / definitions",
    "type": "definition",
    "need": 3,
    "have": 71,
    "ok": true
   },
   {
    "name": "FAQ page",
    "type": "question",
    "need": 5,
    "have": 0,
    "ok": false
   },
   {
    "name": "Comparison page",
    "type": "comparison",
    "need": 6,
    "have": 18,
    "ok": true
   },
   {
    "name": "How-it-works explainer",
    "type": "process",
    "need": 1,
    "have": 0,
    "ok": false
   },
   {
    "name": "Entity / about page",
    "type": "credential",
    "need": 3,
    "have": 0,
    "ok": false
   }
  ],
  "findings": {
   "contradictions": 1,
   "duplicate_urls": 7,
   "orphans": 9,
   "unsourced": 15,
   "spa": 0,
   "no_schema": 16
  },
  "material": [
   {
    "type": "quantity",
    "text": "The package ships 116 laws total \u2014 the remaining 13 are the compose/CC2 laws (& combine \u00b7 |> pipeline \u00b7 \u2297 cross), run separately via node test/compose-laws.mjs.",
    "url": "https://opensentience.org/playground.html"
   },
   {
    "type": "quantity",
    "text": "Docs box-and-box kernel Playground The 103 laws ampersandboxdesign.com graphonomous.com deliberatic.com GitHub [&] Protocol traaviis.com",
    "url": "https://opensentience.org/"
   }
  ]
 },
 {
  "domain": "ampersandboxdesign.com",
  "entity": "[&] Ampersand Box",
  "pages": 6,
  "words": 7301,
  "claims": 397,
  "types": {
   "entity": 0,
   "quantity": 27,
   "quote": 2,
   "definition": 31,
   "comparison": 17,
   "question": 0,
   "credential": 10,
   "process": 0,
   "attribute": 310
  },
  "blocked": [],
  "forms": [
   {
    "name": "Statistics / data page",
    "type": "quantity",
    "need": 5,
    "have": 27,
    "ok": true
   },
   {
    "name": "Glossary / definitions",
    "type": "definition",
    "need": 3,
    "have": 31,
    "ok": true
   },
   {
    "name": "FAQ page",
    "type": "question",
    "need": 5,
    "have": 0,
    "ok": false
   },
   {
    "name": "Comparison page",
    "type": "comparison",
    "need": 6,
    "have": 17,
    "ok": true
   },
   {
    "name": "How-it-works explainer",
    "type": "process",
    "need": 1,
    "have": 0,
    "ok": false
   },
   {
    "name": "Entity / about page",
    "type": "credential",
    "need": 3,
    "have": 10,
    "ok": true
   }
  ],
  "findings": {
   "contradictions": 0,
   "duplicate_urls": 1,
   "orphans": 4,
   "unsourced": 0,
   "spa": 0,
   "no_schema": 6
  },
  "material": [
   {
    "type": "quantity",
    "text": "knowledge (S5) is factive in 100% of cases; belief (KD45) believes a falsehood in ~30% \u2014 the whole point of separating \u201cknows\u201d from \u201cbelieves.\u201d",
    "url": "https://ampersandboxdesign.com/laws.html"
   },
   {
    "type": "quantity",
    "text": "the grand coalition can reach what a soloist can in 100% of games, and strictly more in 25% \u2014 ought-implies-can has teeth.",
    "url": "https://ampersandboxdesign.com/laws.html"
   }
  ]
 },
 {
  "domain": "fleetprompt.com",
  "entity": "FleetPrompt",
  "pages": 1,
  "words": 1231,
  "claims": 66,
  "types": {
   "entity": 0,
   "quantity": 5,
   "quote": 1,
   "definition": 10,
   "comparison": 5,
   "question": 0,
   "credential": 0,
   "process": 0,
   "attribute": 45
  },
  "blocked": [],
  "forms": [
   {
    "name": "Statistics / data page",
    "type": "quantity",
    "need": 5,
    "have": 5,
    "ok": true
   },
   {
    "name": "Glossary / definitions",
    "type": "definition",
    "need": 3,
    "have": 10,
    "ok": true
   },
   {
    "name": "FAQ page",
    "type": "question",
    "need": 5,
    "have": 0,
    "ok": false
   },
   {
    "name": "Comparison page",
    "type": "comparison",
    "need": 6,
    "have": 5,
    "ok": false
   },
   {
    "name": "How-it-works explainer",
    "type": "process",
    "need": 1,
    "have": 0,
    "ok": false
   },
   {
    "name": "Entity / about page",
    "type": "credential",
    "need": 3,
    "have": 0,
    "ok": false
   }
  ],
  "findings": {
   "contradictions": 0,
   "duplicate_urls": 0,
   "orphans": 1,
   "unsourced": 0,
   "spa": 0,
   "no_schema": 1
  },
  "material": [
   {
    "type": "quantity",
    "text": "A FreeBSD 15 distribution assembled from pkgbase: 364 MB and 50 packages in the bare server flavour, 625 MB and 56 once it carries the verifier and the interpreter that runs it.",
    "url": "https://fleetprompt.com/"
   },
   {
    "type": "quantity",
    "text": "The stack costs 14 MB; the interpreter it needs costs rather more, taking the server image from 364 MB to 625 MB and 50 packages to 56.",
    "url": "https://fleetprompt.com/"
   }
  ]
 },
 {
  "domain": "prism.opensentience.org",
  "entity": "PRISM",
  "pages": 1,
  "words": 865,
  "claims": 66,
  "types": {
   "entity": 0,
   "quantity": 1,
   "quote": 1,
   "definition": 4,
   "comparison": 1,
   "question": 0,
   "credential": 1,
   "process": 0,
   "attribute": 58
  },
  "blocked": [],
  "forms": [
   {
    "name": "Statistics / data page",
    "type": "quantity",
    "need": 5,
    "have": 1,
    "ok": false
   },
   {
    "name": "Glossary / definitions",
    "type": "definition",
    "need": 3,
    "have": 4,
    "ok": true
   },
   {
    "name": "FAQ page",
    "type": "question",
    "need": 5,
    "have": 0,
    "ok": false
   },
   {
    "name": "Comparison page",
    "type": "comparison",
    "need": 6,
    "have": 1,
    "ok": false
   },
   {
    "name": "How-it-works explainer",
    "type": "process",
    "need": 1,
    "have": 0,
    "ok": false
   },
   {
    "name": "Entity / about page",
    "type": "credential",
    "need": 3,
    "have": 1,
    "ok": false
   }
  ],
  "findings": {
   "contradictions": 0,
   "duplicate_urls": 0,
   "orphans": 1,
   "unsourced": 0,
   "spa": 0,
   "no_schema": 1
  },
  "material": [
   {
    "type": "quantity",
    "text": "cycle paper-2026 scenarios frozen + seeded export leaderboard CSV",
    "url": "https://prism.opensentience.org/"
   },
   {
    "type": "quote",
    "text": "Each commit boundary is a probe: \"what did the system know before, and what should it infer after?\" The code at HEAD is the oracle.",
    "url": "https://prism.opensentience.org/"
   }
  ]
 },
 {
  "domain": "specprompt.com",
  "entity": "SpecPrompt",
  "pages": 1,
  "words": 1116,
  "claims": 62,
  "types": {
   "entity": 0,
   "quantity": 6,
   "quote": 1,
   "definition": 6,
   "comparison": 3,
   "question": 1,
   "credential": 1,
   "process": 0,
   "attribute": 44
  },
  "blocked": [],
  "forms": [
   {
    "name": "Statistics / data page",
    "type": "quantity",
    "need": 5,
    "have": 6,
    "ok": true
   },
   {
    "name": "Glossary / definitions",
    "type": "definition",
    "need": 3,
    "have": 6,
    "ok": true
   },
   {
    "name": "FAQ page",
    "type": "question",
    "need": 5,
    "have": 1,
    "ok": false
   },
   {
    "name": "Comparison page",
    "type": "comparison",
    "need": 6,
    "have": 3,
    "ok": false
   },
   {
    "name": "How-it-works explainer",
    "type": "process",
    "need": 1,
    "have": 0,
    "ok": false
   },
   {
    "name": "Entity / about page",
    "type": "credential",
    "need": 3,
    "have": 1,
    "ok": false
   }
  ],
  "findings": {
   "contradictions": 0,
   "duplicate_urls": 0,
   "orphans": 1,
   "unsourced": 0,
   "spa": 0,
   "no_schema": 1
  },
  "material": [
   {
    "type": "quantity",
    "text": "Amazon made Kiro, its spec-first IDE, generally available on 17 November 2025, turning prompts into EARS-notation requirements.",
    "url": "https://specprompt.com/"
   },
   {
    "type": "quantity",
    "text": "The industry spent 2025 agreeing that the spec \u2014 not the prompt, not the code \u2014 is the source of truth.",
    "url": "https://specprompt.com/"
   }
  ]
 },
 {
  "domain": "pulse.opensentience.org",
  "entity": "PULSE",
  "pages": 1,
  "words": 866,
  "claims": 59,
  "types": {
   "entity": 0,
   "quantity": 3,
   "quote": 2,
   "definition": 4,
   "comparison": 0,
   "question": 0,
   "credential": 0,
   "process": 0,
   "attribute": 50
  },
  "blocked": [],
  "forms": [
   {
    "name": "Statistics / data page",
    "type": "quantity",
    "need": 5,
    "have": 3,
    "ok": false
   },
   {
    "name": "Glossary / definitions",
    "type": "definition",
    "need": 3,
    "have": 4,
    "ok": true
   },
   {
    "name": "FAQ page",
    "type": "question",
    "need": 5,
    "have": 0,
    "ok": false
   },
   {
    "name": "Comparison page",
    "type": "comparison",
    "need": 6,
    "have": 0,
    "ok": false
   },
   {
    "name": "How-it-works explainer",
    "type": "process",
    "need": 1,
    "have": 0,
    "ok": false
   },
   {
    "name": "Entity / about page",
    "type": "credential",
    "need": 3,
    "have": 0,
    "ok": false
   }
  ],
  "findings": {
   "contradictions": 0,
   "duplicate_urls": 0,
   "orphans": 1,
   "unsourced": 0,
   "spa": 0,
   "no_schema": 1
  },
  "material": [
   {
    "type": "quantity",
    "text": "cadence tick \u00b7 every 30s token OutcomeSignal \u2192 PRISM invariant \u03ba-routing",
    "url": "https://pulse.opensentience.org/"
   },
   {
    "type": "quantity",
    "text": "cadence stream \u00b7 \u226450 ms lag token DeliberationResult invariant \u03ba-routing",
    "url": "https://pulse.opensentience.org/"
   }
  ]
 },
 {
  "domain": "runefort.com",
  "entity": "Runefort",
  "pages": 2,
  "words": 991,
  "claims": 50,
  "types": {
   "entity": 1,
   "quantity": 4,
   "quote": 0,
   "definition": 2,
   "comparison": 4,
   "question": 0,
   "credential": 0,
   "process": 0,
   "attribute": 39
  },
  "blocked": [],
  "forms": [
   {
    "name": "Statistics / data page",
    "type": "quantity",
    "need": 5,
    "have": 4,
    "ok": false
   },
   {
    "name": "Glossary / definitions",
    "type": "definition",
    "need": 3,
    "have": 2,
    "ok": false
   },
   {
    "name": "FAQ page",
    "type": "question",
    "need": 5,
    "have": 0,
    "ok": false
   },
   {
    "name": "Comparison page",
    "type": "comparison",
    "need": 6,
    "have": 4,
    "ok": false
   },
   {
    "name": "How-it-works explainer",
    "type": "process",
    "need": 1,
    "have": 0,
    "ok": false
   },
   {
    "name": "Entity / about page",
    "type": "credential",
    "need": 3,
    "have": 0,
    "ok": false
   }
  ],
  "findings": {
   "contradictions": 0,
   "duplicate_urls": 0,
   "orphans": 1,
   "unsourced": 0,
   "spa": 1,
   "no_schema": 1
  },
  "material": [
   {
    "type": "quantity",
    "text": "Runefort owns nothing \u2014 it's a 5KB protocol you ship inside whatever stack you already have.",
    "url": "https://runefort.com/"
   },
   {
    "type": "quantity",
    "text": "Runefort ships ~5KB of Web Components plus a portable JSON spec for the grid itself.",
    "url": "https://runefort.com/"
   }
  ]
 },
 {
  "domain": "bendscript.com",
  "entity": "BendScript",
  "pages": 2,
  "words": 738,
  "claims": 46,
  "types": {
   "entity": 1,
   "quantity": 4,
   "quote": 1,
   "definition": 3,
   "comparison": 1,
   "question": 0,
   "credential": 0,
   "process": 0,
   "attribute": 36
  },
  "blocked": [],
  "forms": [
   {
    "name": "Statistics / data page",
    "type": "quantity",
    "need": 5,
    "have": 4,
    "ok": false
   },
   {
    "name": "Glossary / definitions",
    "type": "definition",
    "need": 3,
    "have": 3,
    "ok": true
   },
   {
    "name": "FAQ page",
    "type": "question",
    "need": 5,
    "have": 0,
    "ok": false
   },
   {
    "name": "Comparison page",
    "type": "comparison",
    "need": 6,
    "have": 1,
    "ok": false
   },
   {
    "name": "How-it-works explainer",
    "type": "process",
    "need": 1,
    "have": 0,
    "ok": false
   },
   {
    "name": "Entity / about page",
    "type": "credential",
    "need": 3,
    "have": 0,
    "ok": false
   }
  ],
  "findings": {
   "contradictions": 0,
   "duplicate_urls": 0,
   "orphans": 1,
   "unsourced": 0,
   "spa": 1,
   "no_schema": 1
  },
  "material": [
   {
    "type": "quantity",
    "text": "Documents are JSON; canonicalization is RFC 8785 (JCS); ids are CIDv1 with the json multicodec.",
    "url": "https://bendscript.com/"
   },
   {
    "type": "quantity",
    "text": "96 tests passing across parser, hash, mark expansion, harness mechanics verified",
    "url": "https://bendscript.com/"
   }
  ]
 },
 {
  "domain": "geofleetic.com",
  "entity": "GeoFleetic",
  "pages": 1,
  "words": 449,
  "claims": 36,
  "types": {
   "entity": 0,
   "quantity": 1,
   "quote": 0,
   "definition": 2,
   "comparison": 0,
   "question": 0,
   "credential": 0,
   "process": 0,
   "attribute": 33
  },
  "blocked": [],
  "forms": [
   {
    "name": "Statistics / data page",
    "type": "quantity",
    "need": 5,
    "have": 1,
    "ok": false
   },
   {
    "name": "Glossary / definitions",
    "type": "definition",
    "need": 3,
    "have": 2,
    "ok": false
   },
   {
    "name": "FAQ page",
    "type": "question",
    "need": 5,
    "have": 0,
    "ok": false
   },
   {
    "name": "Comparison page",
    "type": "comparison",
    "need": 6,
    "have": 0,
    "ok": false
   },
   {
    "name": "How-it-works explainer",
    "type": "process",
    "need": 1,
    "have": 0,
    "ok": false
   },
   {
    "name": "Entity / about page",
    "type": "credential",
    "need": 3,
    "have": 0,
    "ok": false
   }
  ],
  "findings": {
   "contradictions": 0,
   "duplicate_urls": 0,
   "orphans": 1,
   "unsourced": 0,
   "spa": 0,
   "no_schema": 1
  },
  "material": [
   {
    "type": "quantity",
    "text": "IEEE COMST 2025 research demonstrates digital twins enabling real-time coordination among heterogeneous agents \u2014 vehicles, roadside units, and traffic control centers.",
    "url": "https://geofleetic.com/"
   },
   {
    "type": "definition",
    "text": "GeoFleetic is the Intelligence layer \u2014 spatial awareness where TickTickClock provides temporal.",
    "url": "https://geofleetic.com/"
   }
  ]
 },
 {
  "domain": "ticktickclock.com",
  "entity": "TickTickClock",
  "pages": 1,
  "words": 515,
  "claims": 35,
  "types": {
   "entity": 0,
   "quantity": 1,
   "quote": 0,
   "definition": 3,
   "comparison": 1,
   "question": 0,
   "credential": 0,
   "process": 0,
   "attribute": 30
  },
  "blocked": [],
  "forms": [
   {
    "name": "Statistics / data page",
    "type": "quantity",
    "need": 5,
    "have": 1,
    "ok": false
   },
   {
    "name": "Glossary / definitions",
    "type": "definition",
    "need": 3,
    "have": 3,
    "ok": true
   },
   {
    "name": "FAQ page",
    "type": "question",
    "need": 5,
    "have": 0,
    "ok": false
   },
   {
    "name": "Comparison page",
    "type": "comparison",
    "need": 6,
    "have": 1,
    "ok": false
   },
   {
    "name": "How-it-works explainer",
    "type": "process",
    "need": 1,
    "have": 0,
    "ok": false
   },
   {
    "name": "Entity / about page",
    "type": "credential",
    "need": 3,
    "have": 0,
    "ok": false
   }
  ],
  "findings": {
   "contradictions": 0,
   "duplicate_urls": 0,
   "orphans": 1,
   "unsourced": 0,
   "spa": 0,
   "no_schema": 1
  },
  "material": [
   {
    "type": "quantity",
    "text": "Continual Compositionality & Orchestration (CCO) \u2014 the research direction identified by the continual learning community as most promising for 2026.",
    "url": "https://ticktickclock.com/"
   },
   {
    "type": "comparison",
    "text": "Unlike Transformers, SSMs scale linearly with sequence length while capturing long-range dependencies \u2014 critical for high-frequency sensor streams where Transformer attention becomes prohibitively expensive.",
    "url": "https://ticktickclock.com/"
   }
  ]
 },
 {
  "domain": "deliberatic.com",
  "entity": "Deliberatic",
  "pages": 1,
  "words": 208,
  "claims": 33,
  "types": {
   "entity": 0,
   "quantity": 19,
   "quote": 5,
   "definition": 1,
   "comparison": 2,
   "question": 0,
   "credential": 0,
   "process": 0,
   "attribute": 6
  },
  "blocked": [],
  "forms": [
   {
    "name": "Statistics / data page",
    "type": "quantity",
    "need": 5,
    "have": 19,
    "ok": true
   },
   {
    "name": "Glossary / definitions",
    "type": "definition",
    "need": 3,
    "have": 1,
    "ok": false
   },
   {
    "name": "FAQ page",
    "type": "question",
    "need": 5,
    "have": 0,
    "ok": false
   },
   {
    "name": "Comparison page",
    "type": "comparison",
    "need": 6,
    "have": 2,
    "ok": false
   },
   {
    "name": "How-it-works explainer",
    "type": "process",
    "need": 1,
    "have": 0,
    "ok": false
   },
   {
    "name": "Entity / about page",
    "type": "credential",
    "need": 3,
    "have": 0,
    "ok": false
   }
  ],
  "findings": {
   "contradictions": 0,
   "duplicate_urls": 0,
   "orphans": 1,
   "unsourced": 0,
   "spa": 0,
   "no_schema": 1
  },
  "material": [
   {
    "type": "quantity",
    "text": "When Agent A says \"87% confident\" and Agent B says \"91%,\" those numbers are unverifiable and incomparable.",
    "url": "https://deliberatic.com/"
   },
   {
    "type": "quantity",
    "text": "Du et al. 2023 \u00b7 Wu et al. 2025: \"simple majority voting already achieves most performance gains\"",
    "url": "https://deliberatic.com/"
   }
  ]
 },
 {
  "domain": "delegatic.com",
  "entity": "Delegatic",
  "pages": 1,
  "words": 457,
  "claims": 32,
  "types": {
   "entity": 0,
   "quantity": 2,
   "quote": 0,
   "definition": 0,
   "comparison": 1,
   "question": 0,
   "credential": 0,
   "process": 0,
   "attribute": 29
  },
  "blocked": [],
  "forms": [
   {
    "name": "Statistics / data page",
    "type": "quantity",
    "need": 5,
    "have": 2,
    "ok": false
   },
   {
    "name": "Glossary / definitions",
    "type": "definition",
    "need": 3,
    "have": 0,
    "ok": false
   },
   {
    "name": "FAQ page",
    "type": "question",
    "need": 5,
    "have": 0,
    "ok": false
   },
   {
    "name": "Comparison page",
    "type": "comparison",
    "need": 6,
    "have": 1,
    "ok": false
   },
   {
    "name": "How-it-works explainer",
    "type": "process",
    "need": 1,
    "have": 0,
    "ok": false
   },
   {
    "name": "Entity / about page",
    "type": "credential",
    "need": 3,
    "have": 0,
    "ok": false
   }
  ],
  "findings": {
   "contradictions": 0,
   "duplicate_urls": 0,
   "orphans": 1,
   "unsourced": 0,
   "spa": 0,
   "no_schema": 1
  },
  "material": [
   {
    "type": "quantity",
    "text": "Launching 2026.\u201d stood here, above an email box wired to nothing \u2014 no form, no handler, no destination.",
    "url": "https://delegatic.com/"
   }
  ]
 },
 {
  "domain": "agentelic.com",
  "entity": "Agentelic",
  "pages": 1,
  "words": 384,
  "claims": 31,
  "types": {
   "entity": 0,
   "quantity": 7,
   "quote": 2,
   "definition": 1,
   "comparison": 0,
   "question": 1,
   "credential": 0,
   "process": 0,
   "attribute": 20
  },
  "blocked": [],
  "forms": [
   {
    "name": "Statistics / data page",
    "type": "quantity",
    "need": 5,
    "have": 7,
    "ok": true
   },
   {
    "name": "Glossary / definitions",
    "type": "definition",
    "need": 3,
    "have": 1,
    "ok": false
   },
   {
    "name": "FAQ page",
    "type": "question",
    "need": 5,
    "have": 1,
    "ok": false
   },
   {
    "name": "Comparison page",
    "type": "comparison",
    "need": 6,
    "have": 0,
    "ok": false
   },
   {
    "name": "How-it-works explainer",
    "type": "process",
    "need": 1,
    "have": 0,
    "ok": false
   },
   {
    "name": "Entity / about page",
    "type": "credential",
    "need": 3,
    "have": 0,
    "ok": false
   }
  ],
  "findings": {
   "contradictions": 0,
   "duplicate_urls": 0,
   "orphans": 1,
   "unsourced": 0,
   "spa": 0,
   "no_schema": 1
  },
  "material": [
   {
    "type": "quantity",
    "text": "Gartner predicts over 40% of agentic AI projects will be scrapped by 2027 \u2014 not because the models fail, but because they aren't engineered for reality.",
    "url": "https://agentelic.com/"
   },
   {
    "type": "quantity",
    "text": "57% of organizations have agents in production, but 32% cite quality as the #1 barrier (LangChain, 2026).",
    "url": "https://agentelic.com/"
   }
  ]
 },
 {
  "domain": "agentromatic.com",
  "entity": "AgenTroMatic",
  "pages": 1,
  "words": 377,
  "claims": 26,
  "types": {
   "entity": 0,
   "quantity": 2,
   "quote": 2,
   "definition": 3,
   "comparison": 1,
   "question": 0,
   "credential": 0,
   "process": 0,
   "attribute": 18
  },
  "blocked": [],
  "forms": [
   {
    "name": "Statistics / data page",
    "type": "quantity",
    "need": 5,
    "have": 2,
    "ok": false
   },
   {
    "name": "Glossary / definitions",
    "type": "definition",
    "need": 3,
    "have": 3,
    "ok": true
   },
   {
    "name": "FAQ page",
    "type": "question",
    "need": 5,
    "have": 0,
    "ok": false
   },
   {
    "name": "Comparison page",
    "type": "comparison",
    "need": 6,
    "have": 1,
    "ok": false
   },
   {
    "name": "How-it-works explainer",
    "type": "process",
    "need": 1,
    "have": 0,
    "ok": false
   },
   {
    "name": "Entity / about page",
    "type": "credential",
    "need": 3,
    "have": 0,
    "ok": false
   }
  ],
  "findings": {
   "contradictions": 0,
   "duplicate_urls": 0,
   "orphans": 1,
   "unsourced": 0,
   "spa": 0,
   "no_schema": 1
  },
  "material": [
   {
    "type": "quantity",
    "text": "The date was Q2 2026 and it passed; the box was wired to nothing at all, so every address typed into it went straight to the floor.",
    "url": "https://agentromatic.com/"
   },
   {
    "type": "quote",
    "text": "summarizer \u2192 Legal \"Classification should precede quantification\"",
    "url": "https://agentromatic.com/"
   }
  ]
 },
 {
  "domain": "webhost.systems",
  "entity": "WebHost.Systems",
  "pages": 1,
  "words": 184,
  "claims": 14,
  "types": {
   "entity": 0,
   "quantity": 0,
   "quote": 0,
   "definition": 2,
   "comparison": 0,
   "question": 0,
   "credential": 0,
   "process": 0,
   "attribute": 12
  },
  "blocked": [],
  "forms": [
   {
    "name": "Statistics / data page",
    "type": "quantity",
    "need": 5,
    "have": 0,
    "ok": false
   },
   {
    "name": "Glossary / definitions",
    "type": "definition",
    "need": 3,
    "have": 2,
    "ok": false
   },
   {
    "name": "FAQ page",
    "type": "question",
    "need": 5,
    "have": 0,
    "ok": false
   },
   {
    "name": "Comparison page",
    "type": "comparison",
    "need": 6,
    "have": 0,
    "ok": false
   },
   {
    "name": "How-it-works explainer",
    "type": "process",
    "need": 1,
    "have": 0,
    "ok": false
   },
   {
    "name": "Entity / about page",
    "type": "credential",
    "need": 3,
    "have": 0,
    "ok": false
   }
  ],
  "findings": {
   "contradictions": 0,
   "duplicate_urls": 0,
   "orphans": 1,
   "unsourced": 0,
   "spa": 0,
   "no_schema": 1
  },
  "material": [
   {
    "type": "definition",
    "text": "WebHost.Systems is a multi-runtime AI agent deployment platform.",
    "url": "https://webhost.systems/"
   }
  ]
 },
 {
  "domain": "docs.ampersandboxdesign.com",
  "entity": "Ampersand Box",
  "pages": 1,
  "words": 0,
  "claims": 0,
  "types": {
   "entity": 0,
   "quantity": 0,
   "quote": 0,
   "definition": 0,
   "comparison": 0,
   "question": 0,
   "credential": 0,
   "process": 0,
   "attribute": 0
  },
  "blocked": [],
  "forms": [
   {
    "name": "Statistics / data page",
    "type": "quantity",
    "need": 5,
    "have": 0,
    "ok": false
   },
   {
    "name": "Glossary / definitions",
    "type": "definition",
    "need": 3,
    "have": 0,
    "ok": false
   },
   {
    "name": "FAQ page",
    "type": "question",
    "need": 5,
    "have": 0,
    "ok": false
   },
   {
    "name": "Comparison page",
    "type": "comparison",
    "need": 6,
    "have": 0,
    "ok": false
   },
   {
    "name": "How-it-works explainer",
    "type": "process",
    "need": 1,
    "have": 0,
    "ok": false
   },
   {
    "name": "Entity / about page",
    "type": "credential",
    "need": 3,
    "have": 0,
    "ok": false
   }
  ],
  "findings": {
   "contradictions": 0,
   "duplicate_urls": 0,
   "orphans": 0,
   "unsourced": 0,
   "spa": 1,
   "no_schema": 1
  },
  "material": []
 },
 {
  "domain": "docs.graphonomous.com",
  "entity": "Ampersand Box",
  "pages": 1,
  "words": 0,
  "claims": 0,
  "types": {
   "entity": 0,
   "quantity": 0,
   "quote": 0,
   "definition": 0,
   "comparison": 0,
   "question": 0,
   "credential": 0,
   "process": 0,
   "attribute": 0
  },
  "blocked": [],
  "forms": [
   {
    "name": "Statistics / data page",
    "type": "quantity",
    "need": 5,
    "have": 0,
    "ok": false
   },
   {
    "name": "Glossary / definitions",
    "type": "definition",
    "need": 3,
    "have": 0,
    "ok": false
   },
   {
    "name": "FAQ page",
    "type": "question",
    "need": 5,
    "have": 0,
    "ok": false
   },
   {
    "name": "Comparison page",
    "type": "comparison",
    "need": 6,
    "have": 0,
    "ok": false
   },
   {
    "name": "How-it-works explainer",
    "type": "process",
    "need": 1,
    "have": 0,
    "ok": false
   },
   {
    "name": "Entity / about page",
    "type": "credential",
    "need": 3,
    "have": 0,
    "ok": false
   }
  ],
  "findings": {
   "contradictions": 0,
   "duplicate_urls": 0,
   "orphans": 0,
   "unsourced": 0,
   "spa": 1,
   "no_schema": 1
  },
  "material": []
 },
 {
  "domain": "docs.opensentience.org",
  "entity": "Ampersand Box",
  "pages": 1,
  "words": 0,
  "claims": 0,
  "types": {
   "entity": 0,
   "quantity": 0,
   "quote": 0,
   "definition": 0,
   "comparison": 0,
   "question": 0,
   "credential": 0,
   "process": 0,
   "attribute": 0
  },
  "blocked": [],
  "forms": [
   {
    "name": "Statistics / data page",
    "type": "quantity",
    "need": 5,
    "have": 0,
    "ok": false
   },
   {
    "name": "Glossary / definitions",
    "type": "definition",
    "need": 3,
    "have": 0,
    "ok": false
   },
   {
    "name": "FAQ page",
    "type": "question",
    "need": 5,
    "have": 0,
    "ok": false
   },
   {
    "name": "Comparison page",
    "type": "comparison",
    "need": 6,
    "have": 0,
    "ok": false
   },
   {
    "name": "How-it-works explainer",
    "type": "process",
    "need": 1,
    "have": 0,
    "ok": false
   },
   {
    "name": "Entity / about page",
    "type": "credential",
    "need": 3,
    "have": 0,
    "ok": false
   }
  ],
  "findings": {
   "contradictions": 0,
   "duplicate_urls": 0,
   "orphans": 0,
   "unsourced": 0,
   "spa": 1,
   "no_schema": 1
  },
  "material": []
 },
 {
  "domain": "workbench.opensentience.org",
  "entity": "workbench",
  "pages": 1,
  "words": 0,
  "claims": 0,
  "types": {
   "entity": 0,
   "quantity": 0,
   "quote": 0,
   "definition": 0,
   "comparison": 0,
   "question": 0,
   "credential": 0,
   "process": 0,
   "attribute": 0
  },
  "blocked": [],
  "forms": [
   {
    "name": "Statistics / data page",
    "type": "quantity",
    "need": 5,
    "have": 0,
    "ok": false
   },
   {
    "name": "Glossary / definitions",
    "type": "definition",
    "need": 3,
    "have": 0,
    "ok": false
   },
   {
    "name": "FAQ page",
    "type": "question",
    "need": 5,
    "have": 0,
    "ok": false
   },
   {
    "name": "Comparison page",
    "type": "comparison",
    "need": 6,
    "have": 0,
    "ok": false
   },
   {
    "name": "How-it-works explainer",
    "type": "process",
    "need": 1,
    "have": 0,
    "ok": false
   },
   {
    "name": "Entity / about page",
    "type": "credential",
    "need": 3,
    "have": 0,
    "ok": false
   }
  ],
  "findings": {
   "contradictions": 0,
   "duplicate_urls": 0,
   "orphans": 0,
   "unsourced": 0,
   "spa": 1,
   "no_schema": 1
  },
  "material": []
 }
];

export const EXPANSION = [
 {
  "domain": "opensentience.org",
  "seeds": [
   {
    "term": "continual learning",
    "kind": "supplied",
    "kept": 136,
    "returned": 222
   },
   {
    "term": "knowledge graph memory",
    "kind": "supplied",
    "kept": 189,
    "returned": 195
   },
   {
    "term": "agent memory",
    "kind": "supplied",
    "kept": 166,
    "returned": 199
   },
   {
    "term": "catastrophic forgetting",
    "kind": "supplied",
    "kept": 164,
    "returned": 184
   },
   {
    "term": "ai governance",
    "kind": "supplied",
    "kept": 249,
    "returned": 283
   },
   {
    "term": "deontic logic",
    "kind": "supplied",
    "kept": 96,
    "returned": 120
   }
  ],
  "total": 457,
  "questions": 115,
  "counts": {
   "ready": 5,
   "thin": 110,
   "weak": 137,
   "none": 205
  },
  "ready": [
   {
    "q": "graphiti knowledge graph memory for an agentic world",
    "strong": 8,
    "claims": 12,
    "types": [
     "definition",
     "attribute",
     "quantity",
     "quote"
    ],
    "sources": [
     "https://opensentience.org/",
     "https://opensentience.org/epistemic-arithmetic"
    ]
   },
   {
    "q": "deontic logic and normative systems",
    "strong": 6,
    "claims": 6,
    "types": [
     "definition",
     "comparison",
     "quote",
     "quantity"
    ],
    "sources": [
     "https://opensentience.org/deontic-arithmetic",
     "https://opensentience.org/deontic-arithmetic.html"
    ]
   },
   {
    "q": "when continual learning moves to memory",
    "strong": 5,
    "claims": 14,
    "types": [
     "attribute",
     "definition",
     "quote",
     "quantity"
    ],
    "sources": [
     "https://opensentience.org/",
     "https://opensentience.org/resource-arithmetic"
    ]
   },
   {
    "q": "is continual learning ready for real world challenges",
    "strong": 5,
    "claims": 14,
    "types": [
     "attribute",
     "definition",
     "quote",
     "quantity"
    ],
    "sources": [
     "https://opensentience.org/",
     "https://opensentience.org/epistemic-arithmetic"
    ]
   },
   {
    "q": "knowledge graph machine learning",
    "strong": 5,
    "claims": 11,
    "types": [
     "attribute",
     "definition",
     "quantity",
     "quote"
    ],
    "sources": [
     "https://opensentience.org/",
     "https://opensentience.org/epistemic-arithmetic"
    ]
   }
  ],
  "thin": [
   {
    "q": "knowledge graph memory mcp",
    "strong": 4,
    "claims": 8,
    "types": [
     "attribute",
     "definition",
     "quantity",
     "quote"
    ],
    "sources": [
     "https://opensentience.org/"
    ]
   },
   {
    "q": "knowledge graph memory mcp server",
    "strong": 4,
    "claims": 8,
    "types": [
     "attribute",
     "definition",
     "quantity",
     "quote"
    ],
    "sources": [
     "https://opensentience.org/"
    ]
   },
   {
    "q": "knowledge graph memory by mcp anthropic",
    "strong": 4,
    "claims": 8,
    "types": [
     "attribute",
     "definition",
     "quantity",
     "quote"
    ],
    "sources": [
     "https://opensentience.org/"
    ]
   },
   {
    "q": "memento mcp a knowledge graph memory system for llms",
    "strong": 4,
    "claims": 9,
    "types": [
     "attribute",
     "definition",
     "quantity",
     "quote"
    ],
    "sources": [
     "https://opensentience.org/"
    ]
   },
   {
    "q": "agent memory systems",
    "strong": 4,
    "claims": 5,
    "types": [
     "quote",
     "attribute",
     "definition",
     "quantity"
    ],
    "sources": [
     "https://opensentience.org/"
    ]
   }
  ],
  "none": [
   {
    "q": "catastrophic forgetting",
    "strong": 0,
    "claims": 0,
    "types": [
     "quantity",
     "quote",
     "definition",
     "comparison"
    ],
    "sources": []
   },
   {
    "q": "catastrophic forgetting llm",
    "strong": 0,
    "claims": 0,
    "types": [
     "quantity",
     "quote",
     "definition",
     "comparison"
    ],
    "sources": []
   },
   {
    "q": "catastrophic forgetting in connectionist networks",
    "strong": 0,
    "claims": 0,
    "types": [
     "quantity",
     "quote",
     "definition",
     "comparison"
    ],
    "sources": []
   },
   {
    "q": "catastrophic forgetting ai",
    "strong": 0,
    "claims": 0,
    "types": [
     "quantity",
     "quote",
     "definition",
     "comparison"
    ],
    "sources": []
   },
   {
    "q": "catastrophic forgetting in llms",
    "strong": 0,
    "claims": 0,
    "types": [
     "quantity",
     "quote",
     "definition",
     "comparison"
    ],
    "sources": []
   },
   {
    "q": "catastrophic forgetting paper",
    "strong": 0,
    "claims": 0,
    "types": [
     "quantity",
     "quote",
     "definition",
     "comparison"
    ],
    "sources": []
   },
   {
    "q": "catastrophic forgetting meaning",
    "strong": 0,
    "claims": 0,
    "types": [
     "quantity",
     "quote",
     "definition",
     "comparison"
    ],
    "sources": []
   },
   {
    "q": "catastrophic forgetting in neural networks",
    "strong": 0,
    "claims": 0,
    "types": [
     "quantity",
     "quote",
     "definition",
     "comparison"
    ],
    "sources": []
   }
  ]
 }
];
