/* ---------------------------------------------------------------
   alkeyword — marketing site

   No framework and no build step, same rule as the tool it advertises.

   Every panel renders from data.js, which is generated by
   prototype/runs/site_dataset.py out of real crawl and expansion JSON.
   The two hand-written blocks below (PROBE_RUN, BRIEF_SAMPLE) are
   transcribed from run artifacts committed beside the code, and each
   names the file it came from — nothing on this page is invented,
   because a tool that refuses to fabricate output cannot fabricate
   its own landing page.
   --------------------------------------------------------------- */

import { SURFACES, EXPANSION } from './data.js';

const $  = (s, r) => (r || document).querySelector(s);
const $$ = (s, r) => Array.from((r || document).querySelectorAll(s));
const reduced = matchMedia('(prefers-reduced-motion: reduce)').matches;

const esc = (s) => String(s).replace(/[&<>"]/g, (c) =>
  ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
const num = (n) => n.toLocaleString('en-US');

/* Claim types in the order crawl.py's report() prints them, with the same
   lever annotations. Kept here rather than in the generated data because it
   is presentation, not measurement. */
const TYPE_ROWS = [
  ['entity', ''],
  ['quantity', 'strongest citation lever'],
  ['quote', '2nd strongest lever'],
  ['definition', 'mintable: glossary'],
  ['comparison', 'mintable: comparison page'],
  ['question', 'mintable: FAQ'],
  ['credential', ''],
  ['process', 'mintable: how-it-works'],
  ['attribute', ''],
];

const BAR_CAP = 38;          // crawl.py:647 — "█" * min(38, n)
const PX_PER_BLOCK = 5.6;    // purely visual; the cap is what carries meaning

/* ------------------------------------------------------------------ nav */

const nav = $('#nav');
const onScroll = () => nav.classList.toggle('stuck', scrollY > 8);
addEventListener('scroll', onScroll, { passive: true });
onScroll();

/* ------------------------------------------------------------------ reveal */

if (!reduced && 'IntersectionObserver' in window) {
  const io = new IntersectionObserver((entries) => {
    entries.forEach((e) => {
      if (!e.isIntersecting) return;
      e.target.classList.add('in');
      io.unobserve(e.target);
    });
  }, { rootMargin: '0px 0px -6% 0px', threshold: 0.05 });

  $$('.card, .gap, .st, .seedbox, .refuse, .explorer, table.plain, blockquote')
    .forEach((el, i) => {
      el.classList.add('rv');
      el.style.transitionDelay = (Math.min(i % 6, 4) * 50) + 'ms';
      io.observe(el);
    });
}

/* ------------------------------------------------------------------ totals */

const totals = SURFACES.reduce((a, s) => ({
  pages: a.pages + s.pages, words: a.words + s.words, claims: a.claims + s.claims,
}), { pages: 0, words: 0, claims: 0 });

$('#totPages').textContent = num(totals.pages);
$('#totWords').textContent = num(totals.words);
$('#totClaims').textContent = num(totals.claims);

/* ------------------------------------------------------------------ hero report

   A condensed stage-1 report, rendered from the same numbers the explorer
   uses, then typed in line by line. Condensed because the full report is 40
   lines and a hero is not a scroll target — every line shown is verbatim in
   shape and content, just fewer of them. */

function heroLines(s) {
  const t = s.types;
  const pad = (str, n) => String(str).padEnd(n);
  const lpad = (str, n) => String(str).padStart(n);
  const L = [];

  L.push(`<span class="d">crawling… ${s.pages} pages, ${num(s.words)} words</span>`);
  L.push('');
  L.push('CLAIM GRAPH');
  for (const [type, lever] of TYPE_ROWS) {
    const n = t[type] || 0;
    if (!n && type !== 'question' && type !== 'process') continue;
    const bar = '█'.repeat(Math.min(BAR_CAP, n));
    const tail = n && lever ? `  <span class="d">← ${lever}</span>` : '';
    L.push(`  ${pad(type, 12)}${lpad(n, 4)}  <span class="g">${bar}</span>${tail}`);
  }
  L.push('');
  L.push('MINTABLE');
  for (const f of s.forms) {
    const mark = f.ok ? '<span class="v">✓</span>' : '<span class="r">✗</span>';
    const why = f.ok ? '' : ' <span class="d">— refused, not enough material</span>';
    L.push(`  ${mark} ${pad(f.name, 24)} ${f.have}/${f.need} ${f.type}${why}`);
  }
  L.push('');
  L.push('FREE FINDINGS <span class="d">(no model calls spent)</span>');
  L.push(s.blocked.length
    ? `  <span class="r">⚠</span> robots.txt blocks ${esc(s.blocked.join(', '))}`
    : '  <span class="v">✓</span> robots.txt does not block AI crawlers');
  const f = s.findings;
  if (f.duplicate_urls) L.push(`  <span class="r">⚠</span> ${f.duplicate_urls} duplicate-URL groups   <span class="d">no canonical between them</span>`);
  if (f.orphans)        L.push(`  <span class="r">⚠</span> ${f.orphans} orphaned value pages`);
  if (f.unsourced)      L.push(`  <span class="r">⚠</span> ${f.unsourced} unsourced quantities`);
  L.push(`  <span class="r">⚠</span> ${f.no_schema} of ${s.pages} pages have no schema markup`);
  return L;
}

function typeIn(el, lines) {
  if (reduced) { el.innerHTML = lines.join('\n'); return; }
  el.innerHTML = '';
  let i = 0;
  const caret = '<span class="caret"></span>';
  const step = () => {
    el.innerHTML = lines.slice(0, i).join('\n') + (i < lines.length ? '\n' + caret : '');
    if (i++ < lines.length) setTimeout(step, lines[i - 1] === '' ? 40 : 55);
  };
  step();
}

const heroSurface = SURFACES.find((s) => s.domain === 'opensentience.org') || SURFACES[0];
$('#heroCmd').textContent = `/alkeyword ${heroSurface.domain}`;

/* Hold the type-in until the hero is actually looked at, so a visitor who
   lands mid-page does not scroll up to a finished, static block. */
if ('IntersectionObserver' in window) {
  const heroIO = new IntersectionObserver((es) => {
    if (!es[0].isIntersecting) return;
    heroIO.disconnect();
    typeIn($('#heroOut'), heroLines(heroSurface));
  }, { threshold: 0.25 });
  heroIO.observe($('#heroterm'));
} else {
  typeIn($('#heroOut'), heroLines(heroSurface));
}

/* ------------------------------------------------------------------ explorer */

const rail = $('#rail');
rail.innerHTML = SURFACES.map((s, i) => `
  <button data-i="${i}" class="${i === 0 ? 'on' : ''}">
    <span>${esc(s.domain)}</span><span class="n">${num(s.claims)}</span>
  </button>`).join('');

/* The terminal caps its ASCII bars at 38 blocks, which is right for a terminal
   and wrong for a chart: on a dense surface eight of nine rows hit the cap and
   render identically, so 171 and 2,154 read as equal. Here the bar is
   proportional to the row maximum and a dotted rule marks where the terminal
   stops drawing. Departing from the terminal is the honest choice — a chart
   whose lengths do not encode its numbers is misinformation with a legend. */
function renderGraph(s) {
  /* Scaled to the largest *lever* type, not the largest type outright.
     `attribute` is the heuristic extractor's dump bucket — the documented
     ceiling is that it absorbs roughly three claims in four — so it is
     routinely an order of magnitude above every row that carries meaning, and
     scaling to it flattens the whole chart into stubs. It overflows the track
     instead, hatched, with its real number beside it. Excluding a known
     junk bucket from the scale is a judgement; hiding that it overflowed
     would not be, which is why the overflow is drawn. */
  const levers = TYPE_ROWS.filter(([t]) => t !== 'attribute').map(([t]) => s.types[t] || 0);
  const max = Math.max(...levers, 1);
  const showCap = max > BAR_CAP;

  $('#graph').innerHTML = TYPE_ROWS.map(([type, lever]) => {
    const n = s.types[type] || 0;
    const over = n > max;
    const pct = Math.min(100, (n / max) * 100);
    const capPct = Math.min(100, (BAR_CAP / max) * 100);
    return `
      <div class="grow ${n ? '' : 'zero'}">
        <span class="t">${type}</span>
        <span class="c">${num(n)}</span>
        <span class="bartrack">
          <span class="barwrap">
            ${n ? `<span class="bar ${over ? 'over' : ''}" style="width:${pct}%"></span>` : ''}
            ${showCap ? `<span class="capmark" style="left:${capPct}%"></span>` : ''}
          </span>
          ${over ? '<span class="lever off">← off the scale, and not a lever</span>'
                 : n && lever ? `<span class="lever ${type === 'quantity' ? 'hot' : ''}">← ${lever}</span>`
                 : ''}
        </span>
      </div>`;
  }).join('');

  $('#capNote').hidden = !showCap;
}

function renderVerdicts(s) {
  $('#verdicts').innerHTML = s.forms.map((f) => `
    <div class="vrow ${f.ok ? 'ok' : 'no'}">
      <span class="vmark">${f.ok ? '✓ MINTABLE' : '✗ REFUSED'}</span>
      <span class="vname">${esc(f.name)}</span>
      <span class="vcount">${f.have}/${f.need} ${f.type}</span>
    </div>`).join('');
}

function renderFinds(s) {
  const f = s.findings;
  const cell = (label, value, kind) =>
    `<div class="find ${kind || ''}"><b>${value}</b>${label}</div>`;
  $('#finds').innerHTML = [
    s.blocked.length
      ? cell('AI crawlers blocked', s.blocked.length, 'warn')
      : cell('robots.txt clear', '✓', 'good'),
    cell('self-contradictions', f.contradictions, f.contradictions ? 'warn' : ''),
    cell('duplicate-URL groups', f.duplicate_urls, f.duplicate_urls ? 'warn' : ''),
    cell('orphaned value pages', f.orphans, f.orphans ? 'warn' : ''),
    cell('unsourced quantities', f.unsourced, f.unsourced ? 'warn' : ''),
    cell(`of ${s.pages} pages, no schema`, f.no_schema, f.no_schema ? 'warn' : ''),
  ].join('');
}

function renderMaterial(s) {
  $('#material').innerHTML = s.material.length
    ? s.material.map((m) => `
        <div class="mrow">
          <span class="mt">${esc(m.type)}</span>
          <span class="mq">“${esc(m.text)}”</span>
          <span class="mu">${esc(m.url)}</span>
        </div>`).join('')
    : `<p class="caption" style="margin:0">No claim on this surface falls in the excerpt
       window. That is what a one-page brochure site looks like from here.</p>`;
}

/* A surface that returns zero claims is not a broken panel — on three of these
   it is the single largest finding in the run, and blanking the pane would hide
   it. The crawler flagged the pages needs_headless, so it knows the difference
   between "nothing here" and "nothing I can read". */
function renderEmpty(s) {
  const box = $('#emptyNote');
  const isEmpty = s.claims === 0;
  box.hidden = !isEmpty;
  if (!isEmpty) return;
  box.innerHTML = `
    <div class="vhead">0 claims — and that is the finding</div>
    <p><b>${esc(s.domain)}</b> returned ${s.pages} page${s.pages === 1 ? '' : 's'},
    HTTP 200, and <b>${s.words} words of extractable text</b>. The content is real; it is
    inside a JSON blob in a <code>&lt;script&gt;</code> tag, so an engine's crawler sees
    what this crawler saw — nothing. Not blocked by <code>robots.txt</code>; simply
    unreadable.</p>
    <p style="margin-top:10px">Across the three documentation hosts in this list that is
    <b>458,382 words</b> and <b>229 documents</b> dark — 6.2× everything else on this page
    combined. No keyword tool surfaces it, because there are no keywords to see.</p>`;
}

function select(i) {
  const s = SURFACES[i];
  $$('#rail button').forEach((b, j) => b.classList.toggle('on', i === j));
  const ent = $('#sEntity');
  ent.textContent = s.entity || '—';
  ent.classList.toggle('long', (s.entity || '').length > 22);
  $('#sPages').textContent  = num(s.pages);
  $('#sWords').textContent  = num(s.words);
  $('#sClaims').textContent = num(s.claims);
  renderEmpty(s);
  renderGraph(s);
  renderVerdicts(s);
  renderFinds(s);
  renderMaterial(s);
}

rail.addEventListener('click', (e) => {
  const b = e.target.closest('button');
  if (b) select(+b.dataset.i);
});
select(0);

/* ------------------------------------------------------------------ refusal demo

   Thresholds come from the generated data, so this cannot disagree with the
   crawler even if §4.2 changes. Requirements text for the richer forms comes
   from SKILL.md's generation table. */

const FORM_DETAIL = {
  quantity:   { form: 'Statistics / data page', unit: 'quantity claims',
                extra: 'each with a unit — a bare number is not a statistic' },
  definition: { form: 'Glossary / definitions', unit: 'definition claims',
                extra: 'plus elaborating claims, or it is a stub' },
  question:   { form: 'FAQ page', unit: 'question claims',
                extra: 'phrased the way people actually ask them' },
  comparison: { form: 'Comparison page', unit: 'comparison claims',
                extra: 'across ≥2 entities and ≥2 quantities' },
  process:    { form: 'How-it-works explainer', unit: 'process claims',
                extra: 'with ≥3 ordered steps' },
  credential: { form: 'Entity / about page', unit: 'credential claims',
                extra: 'the things that make the entity checkable' },
};

const FORMS = SURFACES[0].forms.map((f) => ({ type: f.type, name: f.name, need: f.need }));

$('#formpick').innerHTML = FORMS.map((f, i) =>
  `<button data-f="${i}" class="${i === 0 ? 'on' : ''}">${esc(f.name)}</button>`).join('');

const slider = $('#clSlider');
let formIdx = 0;

function paintRefusal() {
  const f = FORMS[formIdx];
  const have = +slider.value;
  const d = FORM_DETAIL[f.type];
  const ok = have >= f.need;

  slider.style.setProperty('--pct', (have / +slider.max * 100) + '%');
  $('#clOut').textContent = have;

  const box = $('#verdictBox');
  box.classList.toggle('ok', ok);
  box.classList.toggle('no', !ok);
  $('#vbHead').textContent = ok ? '✓ mintable' : '✗ refused';
  $('#vbBody').innerHTML = ok
    ? `You have <b>${have}</b> ${d.unit} and a ${esc(f.name.toLowerCase())} needs
       <b>${f.need}</b>. Enough material — this becomes a brief, with every claim attached
       verbatim and its source URL beside it.`
    : `<b>Not yet.</b> A ${esc(f.name.toLowerCase())} needs <b>${f.need}</b> ${d.unit},
       ${esc(d.extra)}. You have <b>${have}</b>. Gather <b>${f.need - have}</b> more and this
       becomes a ready brief — until then the honest answer is that there is nothing here to
       transmute.`;
}

$('#formpick').addEventListener('click', (e) => {
  const b = e.target.closest('button');
  if (!b) return;
  formIdx = +b.dataset.f;
  $$('#formpick button').forEach((x, i) => x.classList.toggle('on', i === formIdx));
  paintRefusal();
});
slider.addEventListener('input', paintRefusal);
paintRefusal();

/* ------------------------------------------------------------------ tabs */

$('#tabs').addEventListener('click', (e) => {
  const b = e.target.closest('button');
  if (!b) return;
  const want = b.dataset.tab;
  $$('#tabs button').forEach((x) => x.classList.toggle('on', x === b));
  $$('.tabpane').forEach((p) => { p.hidden = p.dataset.pane !== want; });
});

/* ---- stage 1 pane: the full report, not the condensed hero version ---- */
$('#paneCrawl').innerHTML = heroLines(heroSurface).join('\n');

/* ---- stage 2a pane ---- */
const exp = EXPANSION[0];
if (exp) {
  $('#eTotal').textContent = num(exp.total);
  $('#eReady').textContent = exp.counts.ready;
  $('#eThin').textContent  = exp.counts.thin;
  $('#eNone').textContent  = exp.counts.none;

  const row = (q, verdict) => `
    <tr>
      <td class="q">${esc(q.q)}</td>
      <td class="vd ${verdict}">${verdict === 'ready' ? '✓ ready'
                                : verdict === 'thin' ? '~ thin' : '✗ none'}</td>
      <td>${verdict === 'none' ? '<span style="color:var(--faint)">nothing on the site touches it</span>'
                               : `${q.strong} strong · ${esc((q.types || []).slice(0, 3).join(', '))}`}</td>
    </tr>`;

  $('#qtable').innerHTML = `
    <thead><tr>
      <th>real query, as typed</th><th>verdict</th><th>material on your site</th>
    </tr></thead>
    <tbody>
      ${exp.ready.slice(0, 4).map((q) => row(q, 'ready')).join('')}
      ${exp.thin.slice(0, 3).map((q) => row(q, 'thin')).join('')}
      ${exp.none.slice(0, 4).map((q) => row(q, 'none')).join('')}
    </tbody>`;
}

/* ---- stage 2b pane ------------------------------------------------------
   Transcribed from prototype/FINDINGS.md § "Stage 2 + 3 — live probe run"
   (2026-08-10) and the 27 cached responses in prototype/.probe_cache/.
   The citation counts below were recounted from that cache, not from memory. */
const PROBE_RUN = [
  '<span class="d">9 questions × 3 runs = 27 calls · perplexity/sonar · $0.1424</span>',
  '',
  'CITED YOUR OWN DOMAIN',
  '  brand      <span class="v">3/3  3/3  3/3</span>   <span class="d">← brand queries fully owned</span>',
  '  category   <span class="r">0/3  0/3</span>        <span class="d">← completely ceded</span>',
  '  claim      <span class="v">3/3</span>  <span class="r">0/3</span>  <span class="v">3/3</span>  <span class="r">0/3</span>',
  '',
  'WHO GETS CITED INSTEAD  <span class="d">(on the ceded category questions)</span>',
  '  deepeval.com · galileo.ai · mastra.ai · getmaxim.ai',
  '  <span class="d">the real competitive set — discovered, not guessed</span>',
  '',
  'G2 — WRONG FACT  <span class="r">⚠ highest urgency</span>',
  '  asked  <span class="d">"…the kernel laws and trial counts — what are the exact numbers?"</span>',
  '  engine <span class="r">"103 laws × 2,000 trials"</span>   <span class="d">3 of 3 runs</span>',
  '  site   <span class="v">"116 laws total"</span>            <span class="d">stated once, buried</span>',
  '',
  '  <span class="d">a second property under the same owner answered</span>',
  '  <span class="r">"15 laws × 1,000 trials"</span>  <span class="d">— single-site crawling cannot see this</span>',
];
$('#paneProbe').innerHTML = PROBE_RUN.join('\n');

/* ---- stage 4 pane -------------------------------------------------------
   An excerpt of brief 1 of 8, verbatim from
   prototype/runs/opensentience.org.briefs.md, which brief.py wrote from the
   same crawl and expansion JSON this page runs on. Regenerate with:
     python3 brief.py runs/<d>.json runs/<d>.expand.json --out runs/<d>.briefs.md */
const BRIEF_SAMPLE = [
  '<span class="g"># Research briefs — opensentience.org</span>',
  '<span class="d">8 briefs · 2 ready to write · 0 need material first</span>',
  '',
  '<span class="g">## 1. Glossary / definition page — READY</span>',
  '<span class="d">Score 68.0 · 11 claims available</span>',
  '',
  'QUESTIONS THIS ANSWERS',
  '  ❓ when continual learning moves to memory',
  '  ❓ is continual learning ready for real world challenges',
  '  🔍 continual learning · continual learning bench · continual learning llms',
  '  <span class="d">…and 55 more in this cluster</span>',
  '',
  'OUTLINE  <span class="d">(each heading mapped to claim IDs)</span>',
  '  <b>Definition</b>                 c0475, c0480, c0430',
  '  <b>How it works in practice</b>   c0045, c0053, c0108, c0466, c0479',
  '',
  'YOUR RAW MATERIAL  <span class="d">— already on your site. Assemble, don\'t research.</span>',
  '  <span class="d">https://opensentience.org/resource-arithmetic</span>',
  '  <span class="b">c0480</span> <span class="d">definition</span> "Capacity is a conserved resource: learning a task',
  '        moves capacity from free to committed (plasticity spent on stability)…"',
  '        <span class="r">⚠ also served at …/resource-arithmetic.html — duplicate URL, no canonical</span>',
  '',
  '  <span class="d">https://opensentience.org/epistemic-arithmetic</span>',
  '  <span class="b">c0430</span> <span class="d">definition</span> "Learning is a truthful public announcement:',
  '        announce(ψ) deletes every world where ψ is false…"',
];
$('#paneBrief').innerHTML = BRIEF_SAMPLE.join('\n');

/* ------------------------------------------------------------------ seeds toggle

   Measured on a live site, identical code and identical claim graph, only the
   seeds differing. Numbers are from SKILL.md's stage-2a table, which is the
   record of that run. */
const SEED_DATA = {
  auto: {
    ready: 0, thin: 3, none: 312,
    note: 'Auto-seeding inherits the extractor\'s bogus definition claims, so the seeds are '
        + 'sentence fragments — “here”, “each phase”, “if the substrate”. 312 queries come back '
        + 'with nothing on the site touching them, and the three that survive are not worth '
        + 'writing. This is the failure mode, reproduced.',
  },
  resolved: {
    ready: 2, thin: 66, none: 9,
    note: 'Same code, same claim graph, same site — only the seeds resolved into real category '
        + 'vocabulary. thin goes from 3 to 66 and none collapses from 312 to 9. This is why the '
        + 'skill instructs the model to supply the seeds itself rather than trusting the '
        + 'heuristic, and why the limitation is documented instead of hidden.',
  },
};

function paintSeeds(which) {
  const d = SEED_DATA[which];
  $('#sdReady').textContent = d.ready;
  $('#sdThin').textContent  = d.thin;
  $('#sdNone').textContent  = d.none;
  $('#seedNote').textContent = d.note;
}
$('#seedpick').addEventListener('click', (e) => {
  const b = e.target.closest('button');
  if (!b) return;
  $$('#seedpick button').forEach((x) => x.classList.toggle('on', x === b));
  paintSeeds(b.dataset.seed);
});
paintSeeds('auto');

/* ------------------------------------------------------------------ the finding

   Both halves of the 103/116 story, using the two claims the dataset builder
   picked out of the crawl on its own — it selects the longest spans of the
   strongest type, and on this site those happen to be exactly the buried
   correct number and the prominent wrong one. */
const os = SURFACES.find((s) => s.domain === 'opensentience.org');
if (os) {
  $('#lawClaims').innerHTML = os.material.map((m) => `
    <div class="mrow">
      <span class="mt">${esc(m.type)} · from the claim graph</span>
      <span class="mq">“${esc(m.text)}”</span>
      <span class="mu">${esc(m.url)}</span>
    </div>`).join('');
}
